### ISSUE TITLE
filter-table的on-selection-change怎么使用？

### ISSUE THREAD

**Issue by GeekSRE** [baidu/NoahV#115]
filter-table的on-selection-change怎么使用？
谢谢，非前端，请举个例子，谢谢。

**Comment by darrenywyu** [comment]
```
<template>
 <nvFilterTable
            :items="items"
            :columns="columns"
            :action="action"
            url="/api/tpl/filterTable"
            :pagination="pagination"
            @on-selection-change="selectionChange"
        />
</template>
<script>
export default {
// othercode
     methods: {
         selectionChange(selectd) {
                console.log(selectd);
         }  
     }
}
</script>
```
如上，供参考，非完整示例，需补充columns等其他配置信息

**Comment by GeekSRE** [comment]
您好，我按照您的示例代码增加了，没生效。我有两个items，我选择第一个items里的值以后，console控制台没打印选择的value，请问是我哪里配置有错吗？

`<template>
	<div class="kubernetes-deployment-list">
		<NvFilterTable :items="items" :columns="columns" url="http://0.0.0.0:8000/api/k8s_deployment" method="get"
		 :pagination="pagination" @on-selection-change="selectionChange" />
	</div>
</template>

<script>
	export default {
		name: "kubernetes-deployment-list-filter-list",
		data() {
			return {
				items: [{
						name: "cluster",
						title: "集群",
						type: "select",
						option: [{
								name: "VCG-测试环境",
								value: "vcg_test"
							},
							{
								name: "VCG-预览环境",
								value: "vcg_pre"
							},
							{
								name: "VCG-生产环境",
								value: "vcg_pro"
							}
						],
						value: "vcg_test",
						required:true
					},

					{
						name: "namespace",
						title: "命名空间",
						type: "select",
						option: [{
								name: "所有命名空间",
								value: "all"
							},
							{
								name: "default",
								value: "default"
							}
						],
						value: "default",
						required: true
					}
				],
				columns: [{
						title: "名称",
						key: "name",
						width: 300
					},
					// {
					// 	title: "标签",
					// 	key: "labels"
					// },
					{
						title: "容器组数量",
						key: "ready_replicas",
						width: 200
					},
					{
						title: "镜像",
						key: "image"
					},
					{
						title: "创建时间",
						key: "creation_timestamp",
						width: 200
					}
				],
				pagination: {
					remote: false,
					defaultPageSize: 10,
					pageSizeOptions: [10, 20, 30, 100]
				}
			};
		},
		methods: {
			selectionChange(selectd) {
				console.log(selectd);
			}
		}

	};
</script>

<style lang="less">
	.kubernetes-deployment-list {
		.noahv-date-picker-wrapper {
			margin-top: 5px;
		}
	}
</style>
`

**Comment by GeekSRE** [comment]
您好，我按照您的示例代码增加了，没生效。我有两个items，我选择第一个items里的值以后，console控制台没打印选择的value，请问是我哪里配置有错吗？
`
<template>
	<div class="kubernetes-deployment-list">
		<NvFilterTable :items="items" :columns="columns" url="http://0.0.0.0:8000/api/k8s_deployment" method="get"
		 :pagination="pagination" @on-selection-change="selectionChange" />
	</div>
</template>

<script>
	export default {
		name: "kubernetes-deployment-list-filter-list",
		data() {
			return {
				items: [{
						name: "cluster",
						title: "集群",
						type: "select",
						option: [{
								name: "VCG-测试环境",
								value: "vcg_test"
							},
							{
								name: "VCG-预览环境",
								value: "vcg_pre"
							},
							{
								name: "VCG-生产环境",
								value: "vcg_pro"
							}
						],
						value: "vcg_test",
						required:true
					},

					{
						name: "namespace",
						title: "命名空间",
						type: "select",
						option: [{
								name: "所有命名空间",
								value: "all"
							},
							{
								name: "default",
								value: "default"
							}
						],
						value: "default",
						required: true
					}
				],
				columns: [{
						title: "名称",
						key: "name",
						width: 300
					},
					// {
					// 	title: "标签",
					// 	key: "labels"
					// },
					{
						title: "容器组数量",
						key: "ready_replicas",
						width: 200
					},
					{
						title: "镜像",
						key: "image"
					},
					{
						title: "创建时间",
						key: "creation_timestamp",
						width: 200
					}
				],
				pagination: {
					remote: false,
					defaultPageSize: 10,
					pageSizeOptions: [10, 20, 30, 100]
				}
			};
		},
		methods: {
			selectionChange(selectd) {
				console.log(selectd);
			}
		}

	};
</script>

<style lang="less">
	.kubernetes-deployment-list {
		.noahv-date-picker-wrapper {
			margin-top: 5px;
		}
	}
</style>
`

**Comment by darrenywyu** [comment]
on-selection-change是针对表格单行数据的选择，如果是在items中配置的select，监听变化使用的是另外一个配置，文档中这个示例描述的就是这种场景，你可以看看：https://noahv.gitee.io/#/doc/template/form#select-fang-fa-jian-ting-shi-li

**Comment by GeekSRE** [comment]
谢谢，已完成功能。
