### ISSUE TITLE
form表单如何添加级联多选的组件

### ISSUE THREAD

**Issue by GeekSRE** [baidu/NoahV#129]
请教一个问题：
在form表单里，怎么添加 级联多选 的组件。我在帮助文档只看到 单选的  type=cascader

**Comment by darrenywyu** [comment]
最新版本已经支持，你可以使用`noahv update`命令升级到最新版本，配置方式详见示例： https://github.com/baidu/NoahV/pull/130/files#diff-060698566a4ecc83de92141d90196f4f

**Comment by GeekSRE** [comment]
> 最新版本已经支持，你可以使用`noahv update`命令升级到最新版本，配置方式详见示例： https://github.com/baidu/NoahV/pull/130/files#diff-060698566a4ecc83de92141d90196f4f

我试了可以选择一级菜单下的多个二级选项。
请问如何能跨一级菜单选择吗？ 
比如 选择北京的百度科技园，百度大厦 ，再选择江苏的南京  这样？谢谢。

**Comment by darrenywyu** [comment]
一级菜单不支持多选，你可以将待选项平铺到二级
