### ISSUE TITLE
初始化仪表盘项目失败

### ISSUE THREAD

**Issue by zhangcaiqian** [baidu/NoahV#16]
按照文档说明，创建仪表盘目录，并执行以下命令
`noahv init --dashboard`

一段时间之后出现报错
/Users/zhangjun/Demo/dashboard
noahv-cli info Creating a new dashboard project in /Users/zhangjun/Demo/dashboard
noahv-cli error get template failed

使用 npm 源：https://registry.npm.taobao.org/
node 版本：v8.11.3
npm 版本：6.9.0

**Comment by darrenywyu** [comment]
您好，发生这个问题的可能原因有：
1.noahv-cli安装版本过低，请确保已经安装最新版本`1.0.7`，可以使用`noahv --version`查看当前安装版本
2.网络原因，无法从Github下载代码，可以手动尝试着`git clone `一个代码库，看看是否有问题

请您按照上述原因排查，有问题随时咨询。

**Comment by zhangcaiqian** [comment]
你好， `clone` 代码暂时解决了问题，可以从模板目录启动仪表盘项目。
检查了  `noahv-cli` 版本，确实为 `1.0.7`。

**Comment by darrenywyu** [comment]
init拉取代码受网络状况影响较大，`noahv-cli`也更新了一个版本`1.0.8`可以查看具体的下载失败原因，你可以再试试看，不行的话通过`clone`也可以。
