### ISSUE TITLE
Is it a part of baidu AIOps ?

### ISSUE THREAD

**Issue by duanshuaimin** [baidu/NoahV#17]

**Comment by duanshuaimin** [comment]
It is the best monitoring tools I ever used

**Comment by darrenywyu** [comment]
Thank you for your approval. In fact, NoahV is a tool or framework that can be used to help build the AIOps Web platform. A large part of Baidu's AIOps web platform is built using it. it helps us improve the efficiency of building the AIOps web platform.

**Comment by duanshuaimin** [comment]
It helps us to make many beautiful dashboards ,it is simple but more productive .
will it open more examples or components ?

**Comment by darrenywyu** [comment]
We are very happy that NoahV can help you. We will continue to maintain and update this project in the future. If you have good ideas or suggestions, you can also maintain and update the NoahV project together with us.
