### ISSUE TITLE
创建页面后的路径有空格

### ISSUE THREAD

**Issue by HZ-GeLiang** [baidu/NoahV#19]
按官网文档走的步骤
![image](https://user-images.githubusercontent.com/16562680/62008785-bd88b600-b189-11e9-82f3-9b8598c94703.png)
然后按在编译的时候就会报错
![image](https://user-images.githubusercontent.com/16562680/62008810-02145180-b18a-11e9-8cab-d3da9cd78493.png)
原因是css类多了一个空格
![image](https://user-images.githubusercontent.com/16562680/62008817-2112e380-b18a-11e9-9f50-80c88f26c6a2.png)

**Comment by darrenywyu** [comment]
应该是复制的时候`test/list`前面复制到空格了，可以先手动处理下，后面在创建的时候我们会做下空格的过滤。

**Comment by darrenywyu** [comment]
在`1.0.9`版本中加入了空格过滤的功能，升级到该版本之后会过滤输入路径中的空格。
