### ISSUE TITLE
Debian 9 下 init 失败 (v1.0.9) EEXIST: file already exists

### ISSUE THREAD

**Issue by buptzhoutian** [baidu/NoahV#22]
初始化项目失败：EEXIST: file already exists

![init](https://user-images.githubusercontent.com/4327236/63669476-b5fe1080-c80c-11e9-9e37-2e54adaf9915.png)

**Comment by darrenywyu** [comment]
Node.js在Debian系统上的文件操作可能存在差异，你可以在如下两种方式中选一种从而继续使用：

**方式一：** 手动将`/home/t2x/baidu/template/common'下的文件移动到`/home/t2x/baidu`下，然后运行`nohav start`命令。

**方式二：** 直接进入到`/home/t2x/baidu/template/common`运行`nohav start`命令。

后续我们也会针对该问题做升级处理。

**Comment by darrenywyu** [comment]
在`1.0.10`版本的`noahv-cli`中已经修复该问题，可以通过运行`noahv upgrade`升级修复。
