### ISSUE TITLE
建议组件库基于 element

### ISSUE THREAD

**Issue by xiwangzishi** [baidu/NoahV#25]
建议组件库基于 element  https://element.eleme.cn/#/zh-CN  这样有大量组件可以用

**Comment by Jamlee** [comment]
这个issue 还是close掉吧

**Comment by darrenywyu** [comment]
当前是基于`iview`组件库的，https://www.iviewui.com/components/slider 可用的组件其实没有太大的差别，如果需要使用到`element`或者其他库的特定功能或者组件，也可以单独在`main.js`中引入，可以考虑使用按需加载的功能减小资源体积。
