### ISSUE TITLE
初始化报错-目录已存在

### ISSUE THREAD

**Issue by siep1221** [baidu/NoahV#26]
执行 noahv init --dashboard后，返回报错：
`/data/project
noahv-cli info Creating a new dashboard project in /data/project
noahv-cli error get template failed

Error info:
{ Error: EEXIST: file already exists, link '/data/project/template/dashboard' -> '/data/project'
    at Object.linkSync (fs.js:938:3)
    at tryRenameSync (/usr/lib/node_modules/noahv-cli/node_modules/fs-extra/lib/move-sync/index.js:40:12)
    at Object.moveSync (/usr/lib/node_modules/noahv-cli/node_modules/fs-extra/lib/move-sync/index.js:22:3)
    at filterGitFile (/usr/lib/node_modules/noahv-cli/lib/getGitTemplate.js:23:8)
    at /usr/lib/node_modules/noahv-cli/lib/getGitTemplate.js:35:13
    at /usr/lib/node_modules/noahv-cli/node_modules/download-git-repo/index.js:43:9
  errno: -17,
  syscall: 'link',
  code: 'EEXIST',
  path: '/data/project/template/dashboard',
  dest: '/data/project' }`
确认是新创建的空目录/data/project，不加--dashboard参数也同样返回，不影响启动，但是启动后提示/api/user 等接口404的错误，怀疑是初始化项目目录时失败导致后续有些组建没有安装上

**Comment by siep1221** [comment]
不知道啥问题，求解答，环境如下：
[root@pro-noahv dashboard]# node -v
v10.16.3
[root@pro-noahv dashboard]# npm -v
6.9.0
[root@pro-noahv dashboard]# noahv -V
1.0.9

**Comment by darrenywyu** [comment]
系统版本是多少呢？

**Comment by siep1221** [comment]
> 系统类型和版本是？

centos 7.6

**Comment by siep1221** [comment]
> 系统类型和版本是？

[root@pro-noahv ~]# cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core) 
有没有微信群之类的，这里沟通效率太低了

**Comment by darrenywyu** [comment]
这个问题确实与`linux`系统的兼容性有关，在最新发布的`noahv-cli`版本`1.0.10`中已经修复，你可以运行`noahv upgrade`命令更新到最新版本。

另外接口404可能和访问链接中没有携带`?em`参数有关，如果希望API接口访问模拟数据，请在参数中携带上`?em`参数，如：`http://ip:port/?em`。

暂时还没有微信交流群，后续会视情况考虑。

**Comment by siep1221** [comment]
> 这个问题确实与`linux`系统的兼容性有关，在最新发布的`noahv-cli`版本`1.0.10`中已经修复，你可以运行`noahv upgrade`命令更新到最新版本。
> 
> 另外接口404可能和访问链接中没有携带`?em`参数有关，如果希望API接口访问模拟数据，请在参数中携带上`?em`参数，如：`http://ip:port/?em`。
> 
> 暂时还没有微信交流群，后续会视情况考虑。

升级后初始化通过了
