### ISSUE TITLE
有关页面json配置的疑问

### ISSUE THREAD

**Issue by hugoren** [baidu/NoahV#27]
首先表示敬意，文档写得清晰，项目质量好，一跑就起来了，效果挺好。
疑问是：关于页面布局JSON配置能写一两个示例吗？如果你们写了，请告诉我放在哪？

**Comment by darrenywyu** [comment]
目前主要提供两种布局配置形式：
1.顶部导航+内容区，
2.顶部导航+侧边导航+内容区

通过`noahv init`出来的项目默认采用的是第一种，[文档官网](https://www.noahv.org)则采用的是第二种
主要通过`src/common/header.js`文件中的`type`值切换，值分别是`header`和`header-sidebar`。

另外本周我们也将更新一种新的布局形式。
