### ISSUE TITLE
npm start无法启动

### ISSUE THREAD

**Issue by jorry** [baidu/NoahV#30]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.10.9
3 info using node@v7.2.0
4 verbose stack Error: missing script: start
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:151:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:61:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:356:5
4 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:320:45)
4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:354:3)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:311:12
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:425:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:412:12)
5 verbose cwd /Users/iqianjin-liujiawei/Desktop/github/NoahV
6 error Darwin 18.2.0
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
8 error node v7.2.0
9 error npm  v3.10.9
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by darrenywyu** [comment]
您好，请参考文档 `快速开始` 部分的步骤安装脚手架工具初始化项目然后启动项目，直接clone下来的代码库是无法启动的。
