### ISSUE TITLE
想问下与amis的应用场景区别是什么

### ISSUE THREAD

**Issue by qianxuemin** [baidu/NoahV#38]

**Comment by darrenywyu** [comment]
NoahV是针对运维管理平台等应用场景中前端开发的一个应用框架，覆盖开发、联调、测试、上线等环节，除了页面模版之外还有结合运维管理平台前端研发经验沉淀出的项目开发的最佳实践，包括项目初始目录结构、组件库、开发辅助工具、开发调试工具、前后端协作解耦、前端路由管理、编译构建、线上运行统计分析等，开发者可以使用定制的页面模版轻松构建页面，也可以借助我们提供的这些开发工具快速高效的开发出自己想要的定制化的平台，灵活性较大。
