### ISSUE TITLE
Can't resolve './Caspanel' in '/chroot/noahv/node_modules/noahv-component/src/components/nv-cascaderSelect'

### ISSUE THREAD

**Issue by OojaxoO** [baidu/NoahV#45]
根据快速开始执行noahv start
命定行报错: ERROR in ./node_modules/noahv-component/src/components/nv-cascaderSelect/cascaderSelect.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib??ref--1-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/noahv-component/src/components/nv-cascaderSelect/cascaderSelect.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve './Caspanel' in '/opt/data/noahv/node_modules/noahv-component/src/components/nv-cascaderSelect'
 @ ./node_modules/noahv-component/src/components/nv-cascaderSelect/cascaderSelect.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib??ref--1-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/noahv-component/src/components/nv-cascaderSelect/cascaderSelect.vue?vue&type=script&lang=js&) 11:16-37
 @ ./node_modules/noahv-component/src/components/nv-cascaderSelect/cascaderSelect.vue?vue&type=script&lang=js&
 @ ./node_modules/noahv-component/src/components/nv-cascaderSelect/cascaderSelect.vue
 @ ./node_modules/noahv-component/src/components/nv-cascaderSelect/index.js
 @ ./node_modules/noahv-component/src/index.js
 @ ./src/main.js
 @ multi ./scripts/dev-client ./src/main.js

访问页面报错: ERROR in ./node_modules/noahv-component/src/components/nv-cascaderSelect/cascaderSelect.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib??ref--1-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/noahv-component/src/components/nv-cascaderSelect/cascaderSelect.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve './Caspanel' in '/opt/data/noahv/node_modules/noahv-component/src/components/nv-cascaderSelect'；
node版本: v12.2.0

**Comment by darrenywyu** [comment]
已修复，执行下`noahv update`，再重新执行`noahv start`。
