### ISSUE TITLE
内网使用noahv init 报错 RCONNREFUSED 127.0.0.1:443

### ISSUE THREAD

**Issue by liulnngit** [baidu/NoahV#49]
at ClientRequest.req.once.err(...\AppData\Roamin\npm\node_modules\noahv-cli\node_modules\got\index.js:73:21)
code:'ECONNREFUSED'
...
请问内网如何用离线安装包的方式进行初始化，谢谢

**Comment by darrenywyu** [comment]
同学你好，如果机器不能连接到公网将无法使用`noahv init`命令直接完成项目初始化，可按如下步骤手动初始化项目：
1.下载项目代码 [压缩包]( https://github.com/baidu/NoahV/archive/master.zip)上传到不能访问公网的机器上
2.解压代码并进入到 `template/common`目录下，其余目录可以删除
3.在上述目录下运行后`noahv start`安装依赖并启动项目，如依赖安装不成功，可以使用内网的NPM镜像。

**Comment by liulnngit** [comment]
谢谢
