### ISSUE TITLE
noahv init 一直卡在Generating template

### ISSUE THREAD

**Issue by pengls** [baidu/NoahV#57]
最新版本的nodejs:
$ node -v
v12.13.0

$ npm -v
6.12.0

**Comment by darrenywyu** [comment]
请按以下步骤排查问题：
1.查看是否能正常从Github使用`git clone`下载项目到本地，如不能请更换网络重试。
2.运行`noahv -V`显示的版本号是否低于`1.0.11`，如低于请运行`noahv upgrade`升级。
