### ISSUE TITLE
路由通过push方式跳转报错

### ISSUE THREAD

**Issue by wsb260** [baidu/NoahV#78]
> 场景是父路由跳转子路由
> 因为noahv的路由功能不支持重定向,所有选择通过编程式用push跳转
> 但是会报以下错误
![image](https://user-images.githubusercontent.com/24216663/70762511-bb677280-1d8b-11ea-808b-9d659dc831fb.png)

然后通过添加以下代码可以消除错误
```
const routerPush = VueRouter.prototype.push;
VueRouter.prototype.push = function push(location) {
    return routerPush.call(this, location)['catch'](error => error);
};
```

不知道有没有人遇见这种错误

**Comment by darrenywyu** [comment]
hello，贴一个你的使用方法吧，包括你的路由配置、push方法在那个页面中写的，访问那个页面报错等信息提供下

**Comment by darrenywyu** [comment]
为什么要在父路由中push子路由的地址呢？

**Comment by wsb260** [comment]
我的诉求是想要进入系统的时候默认进入子路由

**Comment by darrenywyu** [comment]
关联到 #81
